# Generated by Django 4.2.11 on 2024-07-03 10:58

from django.db import migrations, models

def add_reviews(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    Review = apps.get_model("movies", "Review")
    
    # Define the names of the reviewers
    reviewer_names = ["Alice", "Bob", "Charlie", "David", "Eve"]
    review_ratings = [4, 5, 3, 2, 4]

    for movie in Movie.objects.all():
        for name, rating in zip(reviewer_names, review_ratings):
            Review.objects.create(movie=movie, name=name, rating=rating)

class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movie_runtime_alter_movie_title_review"),
    ]

    operations = [
        migrations.RunPython(add_reviews),
    ]
